black {{ black }}
alt_black {{ alt_black }}
red {{ red }}
alt_red {{ alt_red }}
green {{ green }}
alt_green {{ alt_green }}
yellow {{ yellow }}
alt_yellow {{ alt_yellow }}
blue {{ blue }}
alt_blue {{ alt_blue }}
magenta {{ magenta }}
alt_magenta {{ alt_magenta }}
cyan {{ cyan }}
alt_cyan {{ alt_cyan }}
white {{ white }}
alt_white {{ alt_white }}
primary {{ primary }}
secondary {{ secondary }}
tertiary {{ tertiary }}
warning {{ special }}
